### PR TITLE
Update known issues

### PR DESCRIPTION
**Pull request by 1alessandro1**
It shoud target one of the points from [this](https://github.com/dortania/bugtracker/issues/162) issue 

Original Acidanthera's bugtracker issue can be found [here](https://github.com/acidanthera/bugtracker/issues/1514)
I added the link gently provided by @khronokernel in the issue [162](https://github.com/dortania/bugtracker/issues/162)

### CODE REVIEW

**Comment by dhinakg** [comment]
As Big Sur has been released we should be rolling this page into the guide instead.

**Comment by khronokernel** [comment]
Thanks for the PR @1alessandro1! However as Dhinak mentioned we'd like to start rolling information like this earlier into the guide since majority of users do not read the Big Sur pages. And since XhciPortLimit is a vital quirk for many users, I'd like info to be fairly prominent.

I will handle the PR sometime this weekend.

**Comment by 1alessandro1** [comment]
> As Big Sur has been released we should be rolling this page into the guide instead. 

@dhinakg I guess now that the problem with 11.3 is out there, people should map with that quirk disabled in two steps (first from HS01 to SS01, and then the rest from SS02 to SS10) this note should be added into the usb map guide

**Comment by dhinakg** [comment]
What problem with 11.3?

**Comment by 1alessandro1** [comment]
> What problem with 11.3? I'm OOTL

@dhinakg USB mapping problem with XhciPortlimit

**Pull request closed without merging**
