### PR TITLE
Make method 2 of linux installation more clear

### PR DESCRIPTION
**Pull request by brokeyourbike**
It's confusing which partition block to use in the commands, and `dmg2img` command should be adjusted to match the screenshot

### CODE REVIEW

**Comment by 1Revenger1** [comment]
Does img2dmg require sudo? All the other changes look good.

**Comment by 1Revenger1** [comment]
Does img2dmg require sudo? All the other changes look good.

**Comment by brokeyourbike** [comment]
Honestly don't remember, I have used it with `sudo` just like on the screenshot

**Review by 1Revenger1 — APPROVED** [review]
Oh I see. LGTM

**Pull request merged**
