### PR TITLE
Add info about HideAuxiliary

### PR DESCRIPTION
**Pull request by alyxferrari**
Added info about HideAuxiliary to all Intel desktop, laptop, HEDT, and AMD config guides.

### CODE REVIEW

**Comment by 1Revenger1** [comment]
Would it be better to leave it enabled and put a note on the installation page? Hiding recovery is generally useful aside from the initial installation.

**Comment by alyxferrari** [comment]
As a post-install step, people usually transfer their EFI to their drive's ESP anyway, which involves deleting the `com.apple.recovery.boot` folder. Or they can just delete it without transferring their EFI. I also mentioned that if the user would like to hide those entries, they can enable it. If you'd still like me to change it though, I can.

**Comment by 1Revenger1** [comment]
Recovery would still be shown for installed disks, plus auxiliary options (such as UEFI Shell, NVRAM Reset, etc if set). I think most people would prefer to hide entries they don't normally use, though I'm not sure what the best option is here in this specific case.

You've probably helped more people out recently, I'll defer to you about it I guess.

Also, we already have a note on the install process page. Might be worth upgrading it to be in a warning box though.

**Comment by alyxferrari** [comment]
Should be good unless you have an issue with the new `Comment` section I wrote.

**Comment by alyxferrari** [comment]
Converting to a draft until #342 and #343 are merged. Will update this PR with changes for `coffee-lake.md` and `alder-lake.md` afterwards.

**Pull request closed without merging**
