### PR TITLE
AMD SMBIOS info fixup

### PR DESCRIPTION
**Pull request by alyxferrari**
MacPro6,1 and iMac14,2 aren't good practice on AMD systems. MacPro6,1 has no functional benefit over MacPro7,1 with GCN cards, and iMac SMBIOSes expect an Intel integrated GPU, which obviously AMD systems don't have.
I also replaced the example with MacPro7,1, as that's slightly better than iMacPro1,1 (although in practice it probably doesn't matter). MacPro7,1 doesn't require ACPI renames for native USB maps and it has better support under the hood for dedicated GPUs.

### CODE REVIEW

**Comment by alyxferrari** [comment]
I've also seen a couple people fix black screens or getting stuck on IOConsoleUsers after installing the Web Drivers by switching from iMac14,2 to iMacPro1,1.

**Comment by alyxferrari** [comment]
Wait, my bad, I forgot to edit the FX guide as well. I'll do that tomorrow.

**Comment by 1Revenger1** [comment]
FWIW, iMac14,2 doesn't use the iGPU.
You also could move iMacPro6,1 and MP6,1 to be bullets under MP7,1

**Comment by alyxferrari** [comment]
Thanks for letting me know about iMac14,2, I didn't know that. If that's true, then I agree about putting that back in the guide, but I don't with MacPro6,1. I don't know of any situation where it would offer an advantage over MacPro7,1, so imo it shouldn't be encouraged by putting it in the guide. Any thoughts on this?

**Comment by 1Revenger1** [comment]
> 

MacPro6,1 works with older OSes, and I presume works decently well with GCN cards since that is what it uses. ~~Plus it's the trash can, who wouldn't want that~~

**Comment by alyxferrari** [comment]
Finally got around to fixing this up

**Review by 1Revenger1 — APPROVED** [review]

**Comment by fabiosun** [comment]
MacPro7.1 does not work with macOS High Sierra
AMD kernel patches are also for macOS High Sierra

**Comment by alyxferrari** [comment]
It tells you to use iMacPro1,1 if you need High Sierra or Mojave

**Comment by fabiosun** [comment]
Also MacPro6.1 was good
Used in the past with a TitanXp
Black screen with this kind of SMBios  can be caused by various problems

**Comment by alyxferrari** [comment]
We changed it to add MacPro6,1 back. https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html#platforminfo

**Pull request merged**
