### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by HibanaSama**
Fix various typos and mistakes:
* Intel Desktop config.plist:
  * General changes:
    - 45637b7 remove excess `)` from description SSDT-EC; 
    - ~~8de54ec add missing ':' to LegacySchema;~~ 899d3a4 remove excess `:` from LegacySchema;
  * Clarkdale:
     - fb0b55a change the place of Supported OpenCore version (cosmetics);
   * Kaby Lake:
     - 3d08671 fixing double BlacklistAppleUpdate in Security and More in-depth Info of Security sections;
     - 1a9a8c9 add ProcessorType and change SpoofVendor place under PlatformInfo -> Generic;
     - 4c0606b add an item in UpdateSMBIOSMode list under PlatformInfo -> Generic;
   * Comet Lake:
     - 2662708 fix incorrect spelling of Utilities in macserial path under PlatformInfo -> Note about GenSMBIOS;
     - 2fd0352 change note about GenSMBIOS under PlatformInfo -> Info (now repo GenSMBIOS reflected with MacSerial repo, but macserial doesn't support linux (limited to v2.1.2)); 
* Intel Laptop config.plist:
  * General changes:
    - 6187193 fix links to Fixing iServices page;
    - d79f279 fix links to disabling unsupported GPUs under ACPI -> Add;
    - 62a27c4 change links to Troubleshooting section under Cleaning up;
    - 4be231f, d2f2f1b, 87058eb bring to a general style (I think, a general style is good): changed bold font in Reminder About Serial Numbers from `#####` to `** **` under PlatformInfo, removed excess `#` at the end of file, remove dot;
    - 899d3a4 remove excess `:` from LegacySchema;
  * Arrandale:
    - ~~fb9095d~~ 52ade5a change from `Sandy Bridge` to `Arrandale` under PlatformInfo -> Generic;
    - ac63192 ~~found but **not committed**: no info about supported version OpenCore and initial macOS support;~~ add info about supported version OpenCore and initial macOS support;
    - 4cfd6f9 generated and changed SMBIOS info from MacBookPro8,2 to MacBookPro6,1;
   * Broadwell:
     - f0fdda9 remove excess `#` from Configuration Notes under Device Properties -> Add; it makes the text smaller.
     - b7af0f1 fix `.efi` extension from `.ef` to `.efi` under NVRAM -> Add -> More in-depth Info;
   * Skylake:
     - 9897d7f add missing description of Device Properties -> Add section;
   * Comet Lake Plus:
     - f3815b9 ~~found but **not committed**: note about gensmbios~~ change note about GenSMBIOS under PlatformInfo -> Info (see Intel Desktop config.plist -> Comet Lake; macserial v2.1.2 doesn't generate MacBookPro16,2+ values);
   * Icelake:
     - ~~3ac188d~~ 063c950 ~~found but **not committed**: note about gensmbios~~ add note about MacSerial support in Linux under PlatformInfo -> Info (macserial v2.1.2 doesn't generate MacBookPro16,2+ values);
* Intel HEDT config.plist:
  * Nehalem:
    - ff2d73e change from `Ivy bridge E` to `Nehalem` under Kernel -> Emulate;
  * Haswell-E:
    - fb13b0e remove excess space in `npci=0x3000` under NVRAM -> Add -> General Purpose boot-args -> npci=0x2000;
* AMD Desktop config.plist:
  * General changes:
    - a2a21b7 add missing ` to UpdateSMBIOSMode path under Kernel -> Quirks -> More in-depth Info;
  * FX:
    - 7e0a8da add mising `#` to AMD BIOS Settings; this shows this section in the "quick jump" list
  * Zen:
    - 65bc455 fix link to disabling unsupported GPUs under ACPI -> Add;
* Gathering Files:
  - cd9cdfc fix IntelSnowMausi versions from `10.8-10.8` to `10.6-10.8` under Ethernet section;
  - 462f879 fix plural under Must haves -> Legacy "Must haves" kexts;
* Making the installer in macOS:
  - 9fdedd3 remove three links previously leading to the «How to Upgrade to macOS» page, now redirect to the «How to Get Older Versions of macOS» page instead;
* Installation Process: 
  - a418e2a fix a typo under Booting the OpenCore USB;
* Troubleshooting:
  * Kernel Issues:
    - a5f690d fix links to «Stuck after selecting macOS partition in OpenCore» and «Kernel panic on "Wrong CD Clock Frequency" with Icelake laptop» sections;
  * OpenCore Debugging:
    - a5f690d fix links to File Swaps and Disabling all logging sections
  * Understanding the macOS Boot Process:
    - 2875f3a fix links to various issues;
* OpenCore and macOS 11: Big Sur:
  - a5f690d fix link to «Stuck on `ramrod`(^^^^^^^^^^^^^)»

### CODE REVIEW

**Comment by khronokernel** [comment]
PR looks honestly amazing, seriously thank you for all this work. I see you pushed some work fairly recently, are there still things you'd like to work through or you feel this PR's good to merge?

**Comment by HibanaSama** [comment]
Thank you! I think I need to check other files before merging.

**Comment by HibanaSama** [comment]
I have a question. Why is Haswell-E and Broadwell-E not merged into one file? They just have one difference in CpuidData in Emulate.

**Comment by khronokernel** [comment]
We had them merged originally however users kept coping the wrong kernel patches and breaking their build. Similar to how we have FX and Ryzen separate when in reality very little is changed

**Comment by HibanaSama** [comment]
> put the USB stick into your computer;
> remember that your laptop will still default to the internal drive with Windows
These quotes are taken from the first sentence of the Booting the OpenCore USB section (installation-process.md). Is the word «laptop» a typo? Or was it added on purpose?

**Comment by khronokernel** [comment]
It is a typo and should read more like this:

> put the USB stick into your computer;
> Note: most laptops and some desktops will still default to the internal drive with Windows, and you'll need to manually select OpenCore in the BIOS's boot options

**Comment by HibanaSama** [comment]
I think this commit is normal

**Comment by khronokernel** [comment]
Awesome, from a quick skim this PR looks really good. Will look over it in an hour more thoroughly and mention if there's anything I might want to change. Also big props to adding all the changes in your initial message, much appreciated!

**Comment by HibanaSama** [comment]
I didn't found a link to Black screen after picker in the Understanding the macOS Boot Process section. Maybe remove line with `[Black screen after picker](link)`?

**Comment by khronokernel** [comment]
I was unable to edit your PR, so I opened a new one with your changes. Closing this one. Thanks again for the help!

**Pull request closed without merging**
