### PR TITLE
[Big Sur] Add AirportBrcmInjector Plugin Known Issue

### PR DESCRIPTION
**Pull request by Chris2fourlaw**
Removing the non-nic plugin kext solves wifi hardware detection on 94352Z/HMB

### CODE REVIEW

**Comment by Chris2fourlaw** [comment]
Quote from https://github.com/acidanthera/AirportBrcmFixup/releases/tag/2.0.8

> Under 11.0 (Big Sur) plugin AirPortBrcm4360_Injector.kext must be blocked by MaxKernel 19.9.9 or just removed, otherwise it will block loading of AirPortBrcmNIC since class AirPortBrcm4360 is unsupported.

**Comment by kommtzeitkonrad** [comment]
'Removing' here means removing the entry from `Add:Kernel` in `config.plist` and not the kext itself. I think it would be more useful for users to have the full quote from https://github.com/acidanthera/AirportBrcmFixup/blob/master/README.md#please-pay-attention.

**Comment by Chris2fourlaw** [comment]
Smart. I’ll make another commit.

**Comment by vit9696** [comment]
Just put 19.99.99 as a MaxKernel value. Do not remove anything.

**Pull request merged**
