### PR TITLE
Fix error on the command

### PR DESCRIPTION
**Pull request by tiziodcaio**

### CODE REVIEW

**Comment by dhinakg** [comment]
I don't see an error here?

**Comment by tiziodcaio** [comment]
Try to repeat the command twice

**Comment by tiziodcaio** [comment]
> I don't see an error here?

I tried this one in some computer and it worked, the old one not. It's mentioned there too:
Screenshot_2021-04-02-23-17-00-940_org mozilla firefox_beta

**Comment by dhinakg** [comment]
Edge case.

**Comment by tiziodcaio** [comment]
Fixed in https://github.com/dortania/OpenCore-Install-Guide/commit/640633aeb0d7148e0d9f84adb8254eb8ae191d01#

**Pull request closed without merging**
