### PR TITLE
Update ivy-bridge.md

### PR DESCRIPTION
**Pull request by LocTran016**
I've receive a firmware receiving problem and it just a small tip/note for helping new people

### CODE REVIEW

**Comment by LarryGreen016** [comment]
My picture is here:
106561170_311419076929628_5510046802049705339_o

**Comment by khronokernel** [comment]
Little confused, so you're recommending to apply iMac19,1 SMBIOS properties? That sounds like quite a hacky solution to resolve this. Also few other things:

* Please us proper markdown indentation when making a bullet point
* Please keep images locally, especially as this is a private G-Drive where the image could easily be removed by you at any time
* Verify if slightly newer SMBIOS work(ie. iMac14,2)
  * Jumping fro iMac13,1 to iMac19,1 can have ill-effects 
* See if the Dell Skylake fix works:
  * Kernel -> Quirk -> CustomSMBIOSGuid -> True
  * PlatformInfo -> UpdateSMBIOSMode -> Custom
  * PlatformInfo -> Automatic -> True
* Verify the latest build of OpenCorePkg(0.6.0) fixes this with Automatic enabled, as OpenCorePkg have many SMBIOS values updated recently

I should also mention, this fix breaks with 0.6.0, as there's no SmapleFull.plist and is swapped with iMac11,1:
* https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/SampleLegacy.plist

**Comment by LarryGreen016** [comment]
I've tried this and then receive a error here:
Kernel -> Quirk -> CustomSMBIOSGuid -> True
PlatformInfo -> UpdateSMBIOSMode -> Custom
PlatformInfo -> Automatic -> True
Screen Shot 2020-07-23 at 11 26 18
And I DO not recommend using iMac19,1 SMBIOS, there will be a ton of crazy issues if you use that so you should use the one in the guide. Sorry a lot for the misunderstading, by this I mean that after generate all 4 neccessary information and copying them to generic:
The Type part gets copied to Generic -> SystemProductName.
The Serial part gets copied to Generic -> SystemSerialNumber.
The Board Serial part gets copied to Generic -> MLB.
The SmUUID part gets copied to Generic -> SystemUUID.
And then copy/replace them into others quirk like Datahub,...
I also make a video to make it easier to understand what I say (sorry for the quality, it's my screen maximum resolution)
, I've generate a new serial for that so it isn't my Serial Number.
[Video_2020-07-23_044318.zip](https://github.com/dortania/OpenCore-Install-Guide/files/4963890/Video_2020-07-23_044318.zip)
Sorry for this, too: Please keep images locally, especially as this is a private G-Drive where the image could easily be removed by you at any time but I've tried my best to make it upload but it didn't fix (I've tried drag it and then tried to drag it into the comment and copy, paste the link into the commit but didn't work, I'm really sorry for this

**Comment by LarryGreen016** [comment]
Now is the OpenCore 0.5.9 but in newer version, it's replaced with SampleLegacy.plist and I don't know if this fix can be apply in 0.6.0+ (I haven't try OpenCore 0.6.0 because I haven't fixed my laptop with 0.5.9, I need to fix the crazy CFG Lock in laptop so I don't have time to try the newest version)

**Comment by LarryGreen016** [comment]
And although this can solve problems, there is some little issues, too. Although you can still see the CPU name in some tools like Sensei, Geekbench but in the About My Mac (AMM) and System Report, you can't see the Proccessor name (like Dual-Core Intel Core i5 in AMM), only the speed is shown, I don't know if this can fix that problem in here: https://github.com/dortania/OpenCore-Install-Guide/blob/master/clover-conversion/Clover-config.md#cpu

**Comment by LarryGreen016** [comment]
Please don't publish my video then, people on others laptop brand like HP, ASUS may also try it and maybe suffer some kind of problems, here is that config.plist, too:
[SampleFull.zip](https://github.com/dortania/OpenCore-Install-Guide/files/4964308/SampleFull.zip)

**Comment by dhinakg** [comment]
In the video you sent, Automatic is not set to true, so values from Generic will not be used, which means your values are mixed in with values for other SMBIOS (as those are the defaults with SampleLegacy).
Retest with Automatic set to true.

**Comment by LocTran016** [comment]
@dhinakg If I set like this:
Kernel -> Quirk -> CustomSMBIOSGuid -> True
PlatformInfo -> UpdateSMBIOSMode -> Custom
PlatformInfo -> Automatic -> True
I can't open the SystemReport 
But if I change it to the same kind at the video I attached, the problem is solved, I can open About My Mac and System Report
Here are 2 config.plist for more detail if you want:
[DELL FIRMWARE.zip](https://github.com/dortania/OpenCore-Install-Guide/files/4967430/DELL.FIRMWARE.zip)

**Comment by LocTran016** [comment]
# Update for OpenCore 0.6.0:
The problem isn't fixed, I have used the sample.plist (Change into config.plist when in the EFI folder) and I can't open System Information, the issue look like the one I have posted before)

**Pull request closed without merging**
