### PR TITLE
Fix links in the sidebar to Clover Conversions

### PR DESCRIPTION
**Pull request by tiziodcaio**
Integrate the guide "Clover Conversions" to https://dortania.github.io/OpenCore-Install-Guide/clover-conversion/, without do a popup outside the guide

### CODE REVIEW

**Comment by dhinakg** [comment]
This is intentional, we prefer users redo their EFI focused on OpenCore and only use this section for the obscure stuff.

**Comment by tiziodcaio** [comment]
> 
> 
> This is intentional, we prefer users redo their EFI focused on OpenCore and only use this section for the obscure stuff.

Ahhahaha ok I think so, but what about move it to an other repo? Otherwise the guide will builded every time and the GH actions would get slower

**Comment by dhinakg** [comment]
It takes like 3 minutes to build the guide, it's not exactly an issue

**Comment by tiziodcaio** [comment]
> 
> 
> It takes like 3 minutes to build the guide, it's not exactly an issue

k no problem

**Pull request closed without merging**
