### PR TITLE
Add reference to SHA-1 and SHA-256 collection

### PR DESCRIPTION
**Pull request by 1alessandro1**
I suggest to add the option to check the download once it's done, this repository collects many different hashes, users can choose to calculate their SHA-1 (or SHA-256, present in the comments of the markdown file) and compare it with their download. 

Checking the integrity can be useful to prevent MitM attacks or corrupted installers, making all of us safer. It's best practice to do this and many distros are bundled with SHA text files, so I thought it would be nice to provide them (as an option) since they're not harmful

### CODE REVIEW

**Comment by dhinakg** [comment]
I feel it would be better to check using the integrityData from Apple instead of a crowdsourced hash repository, no?

**Comment by 1alessandro1** [comment]
> check using the integrityData from Apple

I did not know about that resource, could you share the link?

**Comment by dhinakg** [comment]
They're in the catalog:
image

It's a chunklist, I can upload a simple verifier when I update the guide.

**Comment by 1alessandro1** [comment]
>  I can upload a simple verifier when I update the guide.

How would that verifier work? Should we paste in a SHA256 (of the Installassistant.pkg?) in a text box? 

If yes, that would be pretty cool to have a simple js script that periodically updates its chuncklists from the catalog, so that anything we download can be later checked by hand if unsure/downloaded from an untrusted source

But the problem is that usually people download the installers and do not have to deal with the .pkgs... I would prefer to use BaseSystem.dmg and InstallESD for 10.15 and below (also, many of the installers are not present in the catalog, e.g. the snow leopard golden master or mavericks installers)

**Comment by dhinakg** [comment]
> How would that verifier work? Should we paste in a SHA256 (of the Installassistant.pkg?) in a text box?

Downloads from gibMacOS or installinstallmacos.py provide the product number in the catalog. Given the product number, the verifier downloads the integrityData (or you could provide it locally, I guess) and checks the checksum (in essence, the chunklist format is just a list of checksums of a chunk of the data at a time) and eventually, the signature too (the chunklist also has a signature.)

> But the problem is that usually people download the installers and do not have to deal with the .pkgs.

That is true. Would like @vit9696's thoughts on this.

**Comment by vit9696** [comment]
Well, as long as a chunklist verifier exists, and it hardcodes Apple public keys, we may be fine even without the SHA-256 hashes of all the models. This is how OpenCore dmg verifier works, for instance.

**Comment by 1alessandro1** [comment]
> [...] we may be fine even without the SHA-256 hashes of all the models.

This is true, but for a specific macOS version e.g. 10.15.x or 10.14.x etc, in my opinion it is a good idea to inform the user that he can check the integrity if his download by running:

For 10.15 and below:

```
shasum /Applications/Install*OS*.app/Contents/SharedSupport/{Base,Install}*.dmg
```

For 11 and above:

```
shasum /Applications/Install*OS*.app/Contents/SharedSupport/SharedSupport.dmg
```

I think this could be only an added value for those who just prefer a quick universally adopted method for hashing, so that with the average user, we can ask them to compute the hash if someone doubts about a patched installer (olarila/niresh images and such - something that OpenCore will certainly notice but it requires the end user to boot that while hashing doesn't)

**Comment by dhinakg** [comment]
Frankly, it doesn't look like I have time to put up a chunklist verifier right now, so I will merge this and then update the guide when I can put up the verifier.

**Review by dhinakg — APPROVED** [review]

**Pull request merged**
