### PR TITLE
Provided more infos about ProvideCustomSlide and EnableSafeModeSlide

### PR DESCRIPTION
**Pull request by dreamwhite**
Original PR: [227](https://github.com/dortania/OpenCore-Install-Guide/pull/227)

Fixed `config.plist/Booter/Quirks` according to OpenCore Configuration.pdf.

In order to determine whether `ProvideCustomSlide` must be enabled (so paired with `EnableSafeModeSlide`) or not, edit the EFI as it follows:

- Use OpenCore DEBUG binaries
- `config.plist/Misc/Debug/Target` set to `67` (so it logs everything in a txt file)

Then boot macOS, and check the txt file by looking for `All slides are usable! You can disable ProvideCustomSlide!`
If you find a match, then disable:

- `config.plist/Booter/Quirks/EnableSafeModeSlide`
- `config.plist/Booter/Quirks/ProvideCustomSlide`

Else, leave them untouched.
Finally restore the OpenCore binaries and set `config.plist/Misc/Debug/Target` set to `3`.

### CODE REVIEW

**Review by tiziodcaio — DISMISSED** [review]
ok good

**Comment by dreamwhite** [comment]
> ok good

Thank you so much  for the approval.
Please let me know if you need any kind of debug log or whatever
Have a nice day
dreamwhite

**Comment by tiziodcaio** [comment]
Now i'll try your guide... lol

**Comment by tiziodcaio** [comment]
Sorry but I can't deactivate it

**Comment by dreamwhite** [comment]
> Sorry but I can't deactivate it There's not the log line...

Ouch, I'm so sorry. May I ask you to provide the .txt log (after stripping the serial numbers) so I can give a look at it? 
Do you have something like `OCABC: Only N/256 slide values are usable!`?

**Comment by tiziodcaio** [comment]
[opencore-2021-02-20-112033.txt](https://github.com/dortania/OpenCore-Install-Guide/files/6015095/opencore-2021-02-20-112033.txt)
No I didn't found nothing

**Comment by dreamwhite** [comment]
> [opencore-2021-02-20-112033.txt](https://github.com/dortania/OpenCore-Install-Guide/files/6015095/opencore-2021-02-20-112033.txt)
> No I didn't found nothing

Uhm wait, may I ask you if you booted macOS?
As far as I know, you'll get the string if you boot macOS :/

**Comment by tiziodcaio** [comment]
> > [opencore-2021-02-20-112033.txt](https://github.com/dortania/OpenCore-Install-Guide/files/6015095/opencore-2021-02-20-112033.txt)
> > No I didn't found nothing
> 
> Uhm wait, may I ask you if you booted macOS?
> As far as I know, you'll get the string if you boot macOS :/
> 
> According to your log, you've booted Windows:
> 
> `21:353 01:297 OCB: Should boot from 1. Windows (T:32|F:0|G:0|E:0|DEF:0)`

Ah lol i misunderstood... Now I'll try

**Comment by tiziodcaio** [comment]
Oh I found All slides are usable! You can disable ProvideCustomSlide! Good job! Thanks

**Comment by dreamwhite** [comment]
> Oh I found All slides are usable! You can disable ProvideCustomSlide! Good job! Thanks

Nice job ^^
I was a little bit scaried about your "I don't see anything" haha.
Please let me know if I have to improve the guide by giving more information, or if the already provided one with this PR are enough ^^

**Comment by tiziodcaio** [comment]
But... It doesn't work... Sorry but I have to retry

**Comment by dreamwhite** [comment]
> But... It doesn't work... Sorry but I have to retry

Wait what you mean by "it doesn't work"?

**Comment by tiziodcaio** [comment]
> 
> 
> > But... It doesn't work... Sorry but I have to retry
> 
> Wait what you mean by "it doesn't work"?

I disabled 
    config.plist/Booter/Quirks/EnableSafeModeSlide
    config.plist/Booter/Quirks/ProvideCustomSlide
but it doesn't work... Now I'm trying whole combos (I don't support MAT, maybe would it be useful?)

**Comment by dreamwhite** [comment]
> > > But... It doesn't work... Sorry but I have to retry
> > 
> > 
> > Wait what you mean by "it doesn't work"?
> 
> I disabled
> config.plist/Booter/Quirks/EnableSafeModeSlide
> config.plist/Booter/Quirks/ProvideCustomSlide
> but it doesn't work... Now I'm trying whole combos (I don't support MAT, maybe would it be useful?) It gave me a panic, but it reboots after and I don't remember how to block it

Well, first of all disable the quirks since they're not needed.
Then ensure to have the following boot-args: `-v debug=0x100 keepsyms=1` and don't forget to add the `boot-args` inside NVRAM/Delete section.
If you want, you can send me via Telegram your config.plist (sry but I don't want to spread serials everywhere) so we can easily find the reason of your KP. My nickname there is @dreamwhitedev

**Comment by tiziodcaio** [comment]
I wrote you on tg. After I retry...

**Comment by khronokernel** [comment]
Looking through the PR, overall looks good to me. Here's my main concerns:

* Missing Desktop pages
  * I assume you left them out to get an idea of what we'll say first
* ~~Info on non-UEFI platforms~~
  * ~~It's rare for Sandy Bridge and Arrendale to have UEFI, maybe we could add info "if hardware supports UEFI"~~
    * Actually just noticed you put them under the UEFI collapsable section, looks good to me!
    
Yeah if you can update those other pages, that would be awesome. Thanks again for the PR!

**Comment by dreamwhite** [comment]
>     * I assume you left them out to get an idea of what we'll say first

Yeah exactly, I'll provide the missing informations and let you know ^^

**Comment by dreamwhite** [comment]
@khronokernel I think we're ready for merging the last changes. 
Please note that, to avoid redundancy of words, I removed `on UEFI platforms` when the paragraph we're talking about `UEFI quirks`. 
Let me know if you need any kind of help, I'm here willing to help you as much as possible.
Have a nice weekend
dreamwhite

**Review by tiziodcaio — APPROVED** [review]

**Comment by khronokernel** [comment]
@dreamwhite So rereading this PR, I feel it may be better to have `EnableSafeModeSlide` and `ProvideCustomSlide` to be enabled by default for all UEFI platforms and in the comments add that it should disabled if `OCABC: All slides are usable! You can disable ProvideCustomSlide!` appears in your logs. 

However, in some spots the information is mismatched, as `EnableSafeModeSlide` is always disabled however on some pages you still have `ProvideCustomSlide` enabled.

I can handle thing change however, so don't worry about updating the PR. Thanks again for the help!

@tiziodcaio Again, please reread our previous conversation in https://github.com/dortania/OpenCore-Install-Guide/pull/235. Please do not abuse the approval system, it creates more problems than it resolves. Next time we will have to take proper action, which we'd prefer not to.

**Comment by tiziodcaio** [comment]
Ok sorry I misunderstood that message :( I won't redo it

**Comment by dreamwhite** [comment]
> @dreamwhite So rereading this PR, I feel it may be better to have `EnableSafeModeSlide` and `ProvideCustomSlide` to be enabled by default for all UEFI platforms and in the comments add that it should disabled if `OCABC: All slides are usable! You can disable ProvideCustomSlide!` appears in your logs. 
> 
> However, in some spots the information is mismatched, as `EnableSafeModeSlide` is always disabled however on some pages you still have `ProvideCustomSlide` enabled.
> 
Oh, I'm so sorry if I mismatched information about that stuff 😅 Next time I'll review the changes twice before pushing the PR haha

> I can handle thing change however, so don't worry about updating the PR. Thanks again for the help!
> 
Your pleasure ^^
I know that sometimes people tend to ignore those simple things to perfect the EFI but I think this is necessary, especially when you're trying to making a perfect job :) 

P.S. despite this PR is a little bit unrelated to my following question: will you ever consider using ocvalidate tool to validate the config.plist? Sometimes it gives us useful informations like the kext order which is not respected everytime by ProperTree, or any mismatched quirks like the one I mentioned in the PR

**Comment by khronokernel** [comment]
> will you ever consider using ocvalidate tool to validate the config.plist? Sometimes it gives us useful informations like the kext order which is not respected everytime by ProperTree, or any mismatched quirks like the one I mentioned in the PR

We plan to actually, just we've been busy with school and work so those projects get thrown to the side.  I'll open an issue about this in our bugtracker, as ocvalidate has been quite useful for finding odd issues especially when updating

**Comment by dreamwhite** [comment]
> > will you ever consider using ocvalidate tool to validate the config.plist? Sometimes it gives us useful informations like the kext order which is not respected everytime by ProperTree, or any mismatched quirks like the one I mentioned in the PR
> 
> We plan to actually, just we've been busy with school and work so those projects get thrown to the side.  I'll open an issue about this in our bugtracker, as ocvalidate has been quite useful for finding odd issues especially when updating

Alright, thank you so much for the approval ^^
I'll try to give a hand whenever needed to help you.
Have a nice day 
dreamwhite

**Pull request merged**
