### PR TITLE
Add guide for offline installer on windows

### PR DESCRIPTION
**Pull request by gmachina**

### CODE REVIEW

**Comment by gmachina** [comment]
khronokernal can i use a free trial software

**Comment by khronokernel** [comment]
Hello, I really appreciate the PR but I can't merge this due to a few issues.

HFS Write support with 3rd party drivers in Windows are very common for corruption, this is the exact reason we don't allow [use of TransMac in our guide](https://dortania.github.io/OpenCore-Install-Guide/CONTRIBUTING.html#contributing-via-prs). I wouldn't feel comfortable recommending users this method, and we would be personally responsible for broken installers if they were to happen. Paragon HFS and Paragon Partition Manager have both been unreliable and have caused corruption in our testing and reports from other users.

You're more than open to host your own installer guide(like what [printf did](https://doesprintfwork.github.io/docs/#/offline-installer-guide/offline-part-2/?id=from-windows)) however we can't endorse this method with these tools.

If you're able to find a reliable, open sourced tool instead we may look into this down the line. We do appreciate the effort you've put into this

**Comment by gmachina** [comment]
> Hello, I really appreciate the PR but I can't merge this due to a few issues.
> 
> HFS Write support with 3rd party drivers in Windows are very common for corruption, this is the exact reason we don't allow [use of TransMac in our guide](https://dortania.github.io/OpenCore-Install-Guide/CONTRIBUTING.html#contributing-via-prs). I wouldn't feel comfortable recommending users this method, and we would be personally responsible for broken installers if they were to happen. Paragon HFS and Paragon Partition Manager have both been unreliable and have caused corruption in our testing and reports from other users.
> 
> You're more than open to host your own installer guide(like what [printf did](https://doesprintfwork.github.io/docs/#/offline-installer-guide/offline-part-2/?id=from-windows)) however we can't endorse this method with these tools.
> 
> If you're able to find a reliable, open sourced tool instead we may look into this down the line. We do appreciate the effort you've put into this

thank you for the information so you mean i can use opensourced reputable software

**Comment by khronokernel** [comment]
Well please pay close attention to reputable, this is where we have the most issues. A single person testing isn't going to give us a proper sample size of real world results, so please keep that in mind when researching

**Comment by gmachina** [comment]
Thank you your response

**Pull request closed without merging**
