### PR TITLE
Grammar fixes in README.md

### PR DESCRIPTION
**Pull request by rvstry**

### CODE REVIEW

**Comment by dhinakg** [comment]
Hey, please fix spellcheck and I'll merge this in.

**Comment by LocTran016** [comment]
The only problem is here I suppose
image

**Comment by rvstry** [comment]
> The only problem is here I suppose
> image

Spellcheck is wrong here, I'll fix the dictionary to reflect this.

**Comment by LocTran016** [comment]
It's the problem with the [spellcheck-cli](https://github.com/tbroadley/spellchecker-cli) 's indefinite-article plugin I guess. See the command [here](https://raw.githubusercontent.com/dortania/OpenCore-Install-Guide/master/package.json).

**Comment by khronokernel** [comment]
Added it to the 0.6.1 branch

**Pull request closed without merging**
