### PR TITLE
Fix typos and add Russian translation

### PR DESCRIPTION
**Pull request by HibanaSama**
Here's fix of minor typos and adding of the Russian translation. sortDict.js doesn't work and I can't commit to the shared folder. 
And one question: why is package-lock.json not included in the .gitignore?
Below is a screenshot of sortDict.js error:
Снимок экрана 2021-01-05 в 21 06 48

### CODE REVIEW

**Comment by HibanaSama** [comment]
I don't know how to cancel commits with merge pull requests to my fork repo :)

**Comment by dhinakg** [comment]
Did you init the submodules? We recently switched to using submodules.

**Comment by HibanaSama** [comment]
Yes, i did it via `git submodule update --init --recursive`, but error is still there when run sort-dict. And also impossible to commit to dictionary.txt via github desktop.
Снимок экрана 2021-01-07 в 13 16 19

**Comment by dhinakg** [comment]
Yea, submodules may have a bit of a learning curve.

If you PR your `dictionary.txt` changes to https://github.com/dortania/build-files I can rerun the CI.

**Comment by HibanaSama** [comment]
> And one question: why is package-lock.json not included in the .gitignore? 

package-lock.json is regenerated on every CI build.

And I found a typo in [Showalldevices](https://github.com/dortania/OpenCore-Install-Guide/blob/master/images/troubleshooting/troubleshooting-md/Showalldevices.png) image. Here should be cmd+2, not cmd+3.

**Comment by HibanaSama** [comment]
Ahhh, spellcheck failed. What to do?

**Comment by khronokernel** [comment]
@HibanaSama Hi, so sorry for the delayed response. Been busy on our end.

Don't worry about spellcheck failing. We'll resolve this in a bit. Thanks the PR again, really appreciate it!

**Comment by HibanaSama** [comment]
Oh, thanks! Sorry for the "Merge pull request" garbage :)

**Pull request merged**
